name: calculator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
